# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  paths:
      exclude:
      -Blazor/*
      include:
      -RazorPages/*

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/AspNetCoreAzureSearch.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'securebuild'
    scannerMode: 'MSBuild'
    projectKey: 'securebuild'
    projectName: 'AspNetCoreAzureSearch'
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'


- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'MSDN - Test Subscription - Rahul Saraf(19608ed5-1579-4ff2-9f5f-a517ca191cb5)'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az group create -l westus -n rg-AspNetCoreAzureSearch
      az appservice plan create -n AspNetCoreAzureSearchplan -g rg-AspNetCoreAzureSearch

- task: AzureCLI@2
  inputs:
    azureSubscription: 'MSDN - Test Subscription - Rahul Saraf(19608ed5-1579-4ff2-9f5f-a517ca191cb5)'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: 'az webapp create -g rg-AspNetCoreAzureSearch -p AspNetCoreAzureSearchplan -n AspNetCoreAzureSearch'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'MSDN - Test Subscription - Rahul Saraf(19608ed5-1579-4ff2-9f5f-a517ca191cb5)'
    appType: 'webApp'
    WebAppName: 'AspNetCoreAzureSearch'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/**/WebApp.zip'